version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "user-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    image: go-user-man-ser
    container_name: "go-user-man-ser"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    depends_on:
      - db 
    networks:
      - fullstack

#  Volume mappings 
volumes:
  database_postgres:

# Allows us to communicate to db and api
networks:
  fullstack:
    driver: bridge
